# input_files is optional, can be a list of file paths or a glob patterns (e.g., "*.fcs" or "**/*.fcs").
input_files:
  - "/home/kiel/stage/flow/data/fcs/*.fcs"

logging:
  log_file: "logs/app.log"
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%dT%H:%M:%S%z"

cache:
  directory: "cache"

plotting:
  backend: "matplotlib" # Options: "matplotlib", "pyqtgraph"
  default_x_channel: "FSC-A"
  default_y_channel: "SSC-A"
  spot_size: 5
  spot_alpha: 0.5
